create table kanji (
    id INT AUTO_INCREMENT PRIMARY KEY,
    literal VARCHAR(2),
    grade INT DEFAULT -1,
    jlpt INT DEFAULT -1,
    freq INT DEFAULT -1,
    meaning VARCHAR(350) DEFAULT "",
    onyomi VARCHAR(350) DEFAULT "",
    kunyomi VARCHAR(350) DEFAULT "",
    nanori VARCHAR(350) DEFAULT ""
);

create table users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(150) NOT NULL,
    password VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

create table comments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userID INT NOT NULL,
    kanjiID INT NOT NULL,
    description VARCHAR(500),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (userID) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (kanjiID) REFERENCES kanji(id) ON DELETE CASCADE
);
